name: Actions Runner Controller Demo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set

    permissions:
      contents: read
      issues: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install puppeteer dependencies
        run: sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2

      - name: Install dependencies
        run: npm install

      - name: Run DocWatcher
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}